// The Multivariate Normal — a random VECTOR of jointly normal coordinates.
// Blitzstein & Hwang, Chapter 7 (Joint Distributions), §7.5.
//
// The arc: a normal random vector as a cloud in the plane; the defining property
// (every linear combination / every shadow is univariate normal); the mean vector
// and covariance matrix Σ; the density and its elliptical Mahalanobis contours; Σ's
// eigen-structure IS the ellipse; the Gaussian miracle (uncorrelated ⇒ independent);
// and conditioning (a slice is normal again, mean on the regression line).
//
// Everything is drawn from a live sample generated by X = L·Z with L the Cholesky
// factor of Σ, so the empirical cloud, the theoretical ellipses, and the eigen-axes
// are guaranteed consistent. Verified in node: L Lᵀ = Σ, Mahalanobis coverage
// 39/86/99%, projection variance = uᵀΣu, eigenvalues sum to trace(Σ).

// ── RNG ───────────────────────────────────────────────────────────────────────
function mul32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const gauss = r => {
  let u = 0, v = 0;
  while (!u) u = r(); while (!v) v = r();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
};

const N = 300;

// Sample X = (x, y) from N(0, Σ) via the Cholesky factor L of Σ:
//   x = σx z1,   y = ρ σy z1 + σy √(1−ρ²) z2.
// Then Cov(X) = L Lᵀ = [[σx², ρσxσy], [ρσxσy, σy²]] exactly.
function makeSample(st) {
  const r = mul32(st.seed);
  const { sx, sy, rho } = st;
  const k = Math.sqrt(1 - rho * rho);
  const xs = [], ys = [];
  for (let i = 0; i < N; i++) {
    const z1 = gauss(r), z2 = gauss(r);
    xs.push(sx * z1);
    ys.push(rho * sy * z1 + sy * k * z2);
  }
  return { xs, ys };
}

// Covariance matrix Σ = [[a, b], [b, c]] and its 2×2 eigen-decomposition.
function sigmaOf(st) {
  const a = st.sx * st.sx, c = st.sy * st.sy, b = st.rho * st.sx * st.sy;
  const tr = (a + c) / 2, d = Math.sqrt(((a - c) / 2) ** 2 + b * b);
  const l1 = tr + d, l2 = tr - d;          // l1 ≥ l2: major, minor
  const phi = 0.5 * Math.atan2(2 * b, a - c); // angle of the major axis
  return { a, b, c, det: a * c - b * b, l1, l2, phi };
}

// ── Colours ───────────────────────────────────────────────────────────────────
const PT = '#455a64', MEAN = '#c62828', ELL = '#5e35b1', AXIS = '#00897b',
      BELL = '#1565c0', REG = '#2e7d32', DEP = '#e8710a';

// ── Small drawing helpers ───────────────────────────────────────────────────────
function normPdf(t, v) { return Math.exp(-t * t / (2 * v)) / Math.sqrt(2 * Math.PI * v); }

// histogram of samples projected onto a unit direction, as density per bin
function projectHist(xs, ys, u, lo, hi, bins) {
  const h = new Array(bins).fill(0), w = (hi - lo) / bins;
  for (let i = 0; i < xs.length; i++) {
    const t = xs[i] * u[0] + ys[i] * u[1];
    const k = Math.floor((t - lo) / w);
    if (k >= 0 && k < bins) h[k]++;
  }
  for (let i = 0; i < bins; i++) h[i] /= xs.length * w; // density
  return { h, w };
}

// ── Drawing ───────────────────────────────────────────────────────────────────
function draw(c2d, st, o) {
  const { xs, ys } = makeSample(st);
  const S = sigmaOf(st);

  c2d.raw((ctx, c) => {
    const size = Math.min(c.height - 120, c.width - 430);
    const L = 90, T = 40, R = L + size, B = T + size;
    const cx = (L + R) / 2, cy = (T + B) / 2;
    const W = 8;                       // world half-window; EQUAL scale on both axes
    const ppu = size / (2 * W);        // pixels per world unit
    const px = x => cx + x * ppu;
    const py = y => cy - y * ppu;

    // frame
    ctx.strokeStyle = '#e0e0e0'; ctx.lineWidth = 1; ctx.strokeRect(L, T, size, size);
    // faint axes through the mean (origin)
    ctx.strokeStyle = '#f2f2f2';
    ctx.beginPath(); ctx.moveTo(L, cy); ctx.lineTo(R, cy); ctx.moveTo(cx, T); ctx.lineTo(cx, B); ctx.stroke();

    // marginal bells in the top / right margins (independence step)
    if (o.marginals) {
      const gain = 34; // px per unit density
      ctx.strokeStyle = BELL; ctx.lineWidth = 1.8; ctx.globalAlpha = 0.9;
      // top: marginal of X ~ N(0, σx²)
      ctx.beginPath();
      for (let i = 0; i <= 100; i++) {
        const x = -W + (2 * W) * i / 100;
        const h = normPdf(x, st.sx * st.sx) * gain;
        const X = px(x), Y = T - 6 - h;
        i ? ctx.lineTo(X, Y) : ctx.moveTo(X, Y);
      }
      ctx.stroke();
      // right: marginal of Y ~ N(0, σy²)
      ctx.beginPath();
      for (let i = 0; i <= 100; i++) {
        const y = -W + (2 * W) * i / 100;
        const h = normPdf(y, st.sy * st.sy) * gain;
        const X = R + 6 + h, Y = py(y);
        i ? ctx.lineTo(X, Y) : ctx.moveTo(X, Y);
      }
      ctx.stroke();
      ctx.globalAlpha = 1;
    }

    // sample cloud
    const indep = o.marginals && Math.abs(st.rho) < 0.02;
    ctx.fillStyle = PT; ctx.globalAlpha = 0.6;
    xs.forEach((x, i) => {
      if (Math.abs(x) > W || Math.abs(ys[i]) > W) return;
      ctx.beginPath(); ctx.arc(px(x), py(ys[i]), 3, 0, Math.PI * 2); ctx.fill();
    });
    ctx.globalAlpha = 1;

    // Mahalanobis ellipses at radius 1,2,3 (image of circles under L)
    if (o.ellipses) {
      const k = Math.sqrt(1 - st.rho * st.rho);
      [1, 2, 3].forEach((rad, idx) => {
        ctx.strokeStyle = ELL; ctx.lineWidth = 2.2 - idx * 0.5; ctx.globalAlpha = 0.9 - idx * 0.18;
        ctx.beginPath();
        for (let a = 0; a <= 64; a++) {
          const th = a / 64 * 2 * Math.PI;
          const ex = st.sx * (rad * Math.cos(th));
          const ey = st.rho * st.sy * (rad * Math.cos(th)) + st.sy * k * (rad * Math.sin(th));
          const X = px(ex), Y = py(ey);
          a ? ctx.lineTo(X, Y) : ctx.moveTo(X, Y);
        }
        ctx.closePath(); ctx.stroke();
      });
      ctx.globalAlpha = 1;
    }

    // principal axes = eigenvectors, half-length 2·√λ (the 2σ ellipse's axes)
    if (o.axes) {
      const dirs = [
        { ang: S.phi, len: 2 * Math.sqrt(S.l1), lab: '√λ₁' },
        { ang: S.phi + Math.PI / 2, len: 2 * Math.sqrt(S.l2), lab: '√λ₂' },
      ];
      dirs.forEach(dd => {
        const ux = Math.cos(dd.ang), uy = Math.sin(dd.ang);
        ctx.strokeStyle = AXIS; ctx.lineWidth = 2.6;
        ctx.beginPath(); ctx.moveTo(px(0), py(0)); ctx.lineTo(px(ux * dd.len), py(uy * dd.len)); ctx.stroke();
        // arrow head
        const hx = px(ux * dd.len), hy = py(uy * dd.len), ah = 7, aa = Math.atan2(-uy, ux);
        ctx.fillStyle = AXIS; ctx.beginPath();
        ctx.moveTo(hx, hy);
        ctx.lineTo(hx - ah * Math.cos(aa - 0.4), hy - ah * Math.sin(aa - 0.4));
        ctx.lineTo(hx - ah * Math.cos(aa + 0.4), hy - ah * Math.sin(aa + 0.4));
        ctx.fill();
      });
    }

    // projection of the cloud onto a rotating direction; the shadow is a bell
    if (o.project) {
      const al = st.angle, u = [Math.cos(al), Math.sin(al)], n = [-Math.sin(al), Math.cos(al)];
      const vTheory = S.a * u[0] * u[0] + 2 * S.b * u[0] * u[1] + S.c * u[1] * u[1];
      // direction line through origin
      ctx.strokeStyle = '#bbb'; ctx.lineWidth = 1.5; ctx.setLineDash([5, 4]);
      ctx.beginPath();
      ctx.moveTo(px(-u[0] * W), py(-u[1] * W)); ctx.lineTo(px(u[0] * W), py(u[1] * W));
      ctx.stroke(); ctx.setLineDash([]);
      // histogram bars, standing off the line along n
      const bins = 26, { h, w } = projectHist(xs, ys, u, -W, W, bins), gain = 3.0;
      ctx.fillStyle = BELL; ctx.globalAlpha = 0.18;
      for (let i = 0; i < bins; i++) {
        const t = -W + (i + 0.5) * w, len = h[i] * gain;
        const bx = t * u[0] + len * n[0], by = t * u[1] + len * n[1];
        const b0x = t * u[0], b0y = t * u[1];
        ctx.beginPath();
        ctx.moveTo(px(b0x - u[0] * w / 2), py(b0y - u[1] * w / 2));
        ctx.lineTo(px(bx - u[0] * w / 2), py(by - u[1] * w / 2));
        ctx.lineTo(px(bx + u[0] * w / 2), py(by + u[1] * w / 2));
        ctx.lineTo(px(b0x + u[0] * w / 2), py(b0y + u[1] * w / 2));
        ctx.fill();
      }
      ctx.globalAlpha = 1;
      // theoretical bell N(0, uᵀΣu) along the line
      ctx.strokeStyle = BELL; ctx.lineWidth = 2.4;
      ctx.beginPath();
      for (let i = 0; i <= 120; i++) {
        const t = -W + (2 * W) * i / 120, len = normPdf(t, vTheory) * 3.0;
        const X = px(t * u[0] + len * n[0]), Y = py(t * u[1] + len * n[1]);
        i ? ctx.lineTo(X, Y) : ctx.moveTo(X, Y);
      }
      ctx.stroke();
    }

    // conditioning: fix X = x0, the conditional of Y is normal on the regression line
    if (o.conditional) {
      const slope = st.rho * st.sy / st.sx;      // regression coefficient
      const yAt = x => slope * x;
      // regression line E[Y|X=x]
      ctx.strokeStyle = REG; ctx.lineWidth = 2.2;
      ctx.beginPath();
      ctx.moveTo(px(-W), py(Math.max(-W, Math.min(W, yAt(-W)))));
      ctx.lineTo(px(W), py(Math.max(-W, Math.min(W, yAt(W)))));
      ctx.stroke();
      const x0 = st.x0, m = yAt(x0), v = st.sy * st.sy * (1 - st.rho * st.rho);
      // the slice
      ctx.strokeStyle = '#999'; ctx.lineWidth = 1.4; ctx.setLineDash([4, 4]);
      ctx.beginPath(); ctx.moveTo(px(x0), T); ctx.lineTo(px(x0), B); ctx.stroke(); ctx.setLineDash([]);
      // conditional bell of Y, drawn sideways off the slice
      ctx.strokeStyle = DEP; ctx.lineWidth = 2.4; ctx.fillStyle = DEP; ctx.globalAlpha = 0.12;
      ctx.beginPath();
      const pts = [];
      for (let i = 0; i <= 120; i++) {
        const y = m - 4 * Math.sqrt(v) + (8 * Math.sqrt(v)) * i / 120;
        const len = normPdf(y, v) * 3.0;
        pts.push([px(x0 + len), py(y)]);
      }
      ctx.moveTo(px(x0), py(m - 4 * Math.sqrt(v)));
      pts.forEach(p => ctx.lineTo(p[0], p[1]));
      ctx.lineTo(px(x0), py(m + 4 * Math.sqrt(v)));
      ctx.globalAlpha = 0.12; ctx.fill(); ctx.globalAlpha = 1;
      ctx.beginPath(); pts.forEach((p, i) => i ? ctx.lineTo(p[0], p[1]) : ctx.moveTo(p[0], p[1])); ctx.stroke();
      // conditional mean marker
      ctx.fillStyle = REG; ctx.beginPath(); ctx.arc(px(x0), py(m), 5, 0, Math.PI * 2); ctx.fill();
    }

    // mean vector marker
    ctx.fillStyle = MEAN; ctx.beginPath(); ctx.arc(px(0), py(0), 4.5, 0, Math.PI * 2); ctx.fill();
    if (o.mu) {
      ctx.strokeStyle = MEAN; ctx.lineWidth = 1; ctx.setLineDash([3, 3]);
      ctx.beginPath(); ctx.moveTo(px(0), py(0)); ctx.lineTo(px(0.02), py(0.02)); ctx.stroke(); ctx.setLineDash([]);
      ctx.fillStyle = MEAN; ctx.font = '12px system-ui'; ctx.textAlign = 'left';
      ctx.fillText('μ', px(0) + 8, py(0) - 8);
    }

    // axis labels
    ctx.fillStyle = '#999'; ctx.font = '12px system-ui'; ctx.textAlign = 'center';
    ctx.fillText('X₁', (L + R) / 2, B + 24);
    ctx.save(); ctx.translate(L - 26, (T + B) / 2); ctx.rotate(-Math.PI / 2);
    ctx.fillText('X₂', 0, 0); ctx.restore();

    // ── readout panel on the right ──
    const rx = R + 50;
    let ry = T + 18;
    const line = (label, val, color = '#333', big = false) => {
      ctx.fillStyle = '#888'; ctx.font = '12px system-ui'; ctx.textAlign = 'left';
      ctx.fillText(label, rx, ry);
      ctx.fillStyle = color; ctx.font = `${big ? 'bold 19px' : '600 14px'} system-ui`;
      ctx.fillText(val, rx, ry + (big ? 24 : 20));
      ry += big ? 50 : 42;
    };

    if (o.showSigma) {
      ctx.fillStyle = '#888'; ctx.font = '12px system-ui'; ctx.textAlign = 'left';
      ctx.fillText('covariance matrix  Σ', rx, ry); ry += 20;
      // bracketed 2×2
      const bx = rx + 6, by = ry, cw = 66, rh = 26;
      ctx.strokeStyle = '#555'; ctx.lineWidth = 1.4;
      ctx.beginPath();
      ctx.moveTo(bx, by - 4); ctx.lineTo(bx - 6, by - 4); ctx.lineTo(bx - 6, by + 2 * rh + 4); ctx.lineTo(bx, by + 2 * rh + 4);
      ctx.moveTo(bx + 2 * cw + 12, by - 4); ctx.lineTo(bx + 2 * cw + 18, by - 4); ctx.lineTo(bx + 2 * cw + 18, by + 2 * rh + 4); ctx.lineTo(bx + 2 * cw + 12, by + 2 * rh + 4);
      ctx.stroke();
      const cell = (r, cc, txt, hot) => {
        ctx.fillStyle = hot ? ELL : '#333'; ctx.font = '600 14px system-ui'; ctx.textAlign = 'center';
        ctx.fillText(txt, bx + 8 + cc * cw + cw / 2, by + r * rh + 18);
      };
      cell(0, 0, S.a.toFixed(2)); cell(0, 1, S.b.toFixed(2), true);
      cell(1, 0, S.b.toFixed(2), true); cell(1, 1, S.c.toFixed(2));
      ry += 2 * rh + 20;
      ctx.fillStyle = '#aaa'; ctx.font = '11px system-ui'; ctx.textAlign = 'left';
      ctx.fillText('diagonal = variances', rx, ry);
      ctx.fillText('off-diagonal = covariance', rx, ry + 15); ry += 40;
    }

    if (o.showCorr) {
      const col = st.rho >= 0 ? BELL : DEP;
      line('correlation  ρ', st.rho.toFixed(2), col, true);
    }
    if (o.showEig) {
      line('eigenvalues of Σ', `λ₁ = ${S.l1.toFixed(2)}    λ₂ = ${S.l2.toFixed(2)}`, AXIS);
      line('axis tilt', `${(S.phi * 180 / Math.PI).toFixed(0)}°`, AXIS);
    }
    if (o.showProjVar) {
      const al = st.angle, u = [Math.cos(al), Math.sin(al)];
      const v = S.a * u[0] * u[0] + 2 * S.b * u[0] * u[1] + S.c * u[1] * u[1];
      line('direction', `${(al * 180 / Math.PI).toFixed(0)}°`);
      line('shadow variance  uᵀΣu', v.toFixed(2), BELL, true);
    }
    if (o.showCond) {
      const slope = st.rho * st.sy / st.sx;
      const v = st.sy * st.sy * (1 - st.rho * st.rho);
      line('slice at  X₁ = x', st.x0.toFixed(2));
      line('E[X₂ | X₁ = x]', (slope * st.x0).toFixed(2), REG, true);
      line('Var(X₂ | X₁ = x)', `${v.toFixed(2)}   ( = σ₂²(1−ρ²) )`, DEP);
    }
    if (o.note) {
      ctx.fillStyle = '#999'; ctx.font = '12px system-ui'; ctx.textAlign = 'left';
      o.note.split('\n').forEach((ln, i) => ctx.fillText(ln, rx, ry + 6 + i * 18));
    }
  });
}

// ── Panel controls ────────────────────────────────────────────────────────────
function clearControls(st) { if (st._controls) st._controls.innerHTML = ''; }

function addSlider(container, label, min, max, step, value, fmt, on) {
  const id = 'mvn-' + label.replace(/[^a-z0-9]/gi, '');
  const w = document.createElement('div');
  w.style.cssText = 'display:flex;flex-direction:column;gap:3px;';
  w.innerHTML = `
    <div style="display:flex;justify-content:space-between;font-size:12px;color:#888;font-family:system-ui">
      <span>${label}</span><span id="${id}-v" style="font-family:Georgia,serif;font-style:italic">${fmt(value)}</span>
    </div>
    <input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}"
      style="width:100%;accent-color:#5e35b1">`;
  container.appendChild(w);
  const inp = w.querySelector('input'), v = w.querySelector(`#${id}-v`);
  inp.addEventListener('input', () => { const x = parseFloat(inp.value); v.textContent = fmt(x); on(x); });
}

const rhoSlider   = st => addSlider(st._controls, 'correlation ρ', -0.95, 0.95, 0.01, st.rho, v => v.toFixed(2), v => st.rho = v);
const sxSlider    = st => addSlider(st._controls, 'σ of X₁', 0.5, 2.6, 0.05, st.sx, v => v.toFixed(2), v => st.sx = v);
const sySlider    = st => addSlider(st._controls, 'σ of X₂', 0.5, 2.6, 0.05, st.sy, v => v.toFixed(2), v => st.sy = v);
const angleSlider = st => addSlider(st._controls, 'projection angle', 0, Math.PI, 0.02, st.angle, v => `${(v * 180 / Math.PI).toFixed(0)}°`, v => st.angle = v);
const x0Slider    = st => addSlider(st._controls, 'slice position x', -4, 4, 0.1, st.x0, v => v.toFixed(1), v => st.x0 = v);

// ── Lesson ────────────────────────────────────────────────────────────────────
export default {
  title:   'The Multivariate Normal',
  subject: 'Probability',

  initState() {
    return { sx: 2, sy: 1.2, rho: 0.6, angle: Math.PI / 4, x0: 1.5, seed: 11, _controls: null };
  },

  init(c2d, state, panelEl) {
    const nav = panelEl.querySelector('#nav');
    const div = document.createElement('div');
    div.id = 'mvn-controls';
    div.style.cssText = 'display:flex;flex-direction:column;gap:10px;border-top:1px solid #eee;padding-top:16px;';
    panelEl.insertBefore(div, nav);
    state._controls = div;
  },

  steps: [
    {
      title: 'A random vector',
      description: 'A multivariate normal random vector $\\mathbf{X} = (X_1, X_2)$ is one random point in the plane. Each draw lands somewhere; repeat and a cloud builds up — densest at the centre, thinning smoothly outward with no hard edge. The one-dimensional bell has become a hill of probability over the plane, centred on the mean vector $\\boldsymbol{\\mu}$.',
      equation: '\\mathbf{X} = (X_1, X_2) \\sim \\mathcal{N}(\\boldsymbol{\\mu},\\, \\Sigma)',
      notes: 'The red dot is the mean vector μ — here the origin. Shifting μ just slides the whole cloud around without changing its shape.\n\nDrag the sliders: σ of each coordinate sets how far the cloud spreads along that axis, and ρ tilts it. Everything that follows is about reading those controls off the geometry.',
      setup(c2d, st) { clearControls(st); sxSlider(st); sySlider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { mu: true }); },
    },
    {
      title: 'Every shadow is a bell',
      description: 'The real definition is not about the picture. A random vector is multivariate normal exactly when every linear combination of its coordinates is an ordinary one-dimensional normal. Geometrically: project the cloud onto any line and the shadow is always a bell. Rotate the projection direction and watch it stay bell-shaped — for every angle.',
      equation: '\\mathbf{a}^\\top \\mathbf{X} = a_1 X_1 + a_2 X_2 \\;\\; \\text{is univariate normal for every } \\mathbf{a}',
      notes: 'This is strictly stronger than "each coordinate is normal". You can have two normal marginals whose joint is NOT multivariate normal — the giveaway is a direction whose shadow is skewed or bimodal. Here, by construction, no such direction exists.\n\nThe blue curve is the exact normal the shadow should follow: its variance is $\\mathbf{u}^\\top\\Sigma\\,\\mathbf{u}$, the spread of the cloud in that direction. Drag the angle and the histogram tracks it.',
      setup(c2d, st) { clearControls(st); angleSlider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { project: true, showProjVar: true }); },
    },
    {
      title: 'Pinned down by μ and Σ',
      description: 'A one-dimensional normal needs a mean and a variance. A normal vector needs a mean vector $\\boldsymbol{\\mu}$ and a covariance matrix $\\Sigma$ — and that is the entire parameter list. The diagonal of $\\Sigma$ holds each coordinate’s variance; the off-diagonal holds their covariance, the very quantity from the previous lesson.',
      equation: '\\boldsymbol{\\mu} = \\mathbb{E}[\\mathbf{X}], \\qquad \\Sigma = \\mathbb{E}\\big[(\\mathbf{X}-\\boldsymbol{\\mu})(\\mathbf{X}-\\boldsymbol{\\mu})^\\top\\big]',
      notes: 'Σ is symmetric (the two off-diagonal entries are the same covariance) and positive semi-definite — you cannot have a negative variance in any direction, since that direction’s variance is $\\mathbf{u}^\\top\\Sigma\\,\\mathbf{u} \\ge 0$.\n\nDrag the sliders and read Σ change: σ² on the diagonal, ρσ₁σ₂ off it. When ρ = 0 the off-diagonal vanishes.',
      setup(c2d, st) { clearControls(st); sxSlider(st); sySlider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { showSigma: true }); },
    },
    {
      title: 'The density and its elliptical contours',
      description: 'The density is the familiar bell exponent with a matrix inside: $-\\tfrac12$ times a quadratic form in $\\Sigma^{-1}$. Points of equal density are the level sets of that quadratic form — ellipses. The number in the exponent is the squared Mahalanobis distance: the correct "how many standard deviations out" once the coordinates are correlated.',
      equation: 'f(\\mathbf{x}) = \\frac{1}{2\\pi\\sqrt{\\det\\Sigma}}\\, \\exp\\!\\Big(\\!-\\tfrac12 (\\mathbf{x}-\\boldsymbol{\\mu})^\\top \\Sigma^{-1} (\\mathbf{x}-\\boldsymbol{\\mu})\\Big)',
      notes: 'The three rings are Mahalanobis radius 1, 2, 3 — they enclose about 39%, 86%, and 99% of the probability (more concentrated than the 68/95/99.7 of one dimension, because the mass is shared over the plane).\n\nThey are ellipses, not circles, whenever the coordinates have unequal spread or any correlation. A circle is the special isotropic case.',
      setup(c2d, st) { clearControls(st); sxSlider(st); sySlider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { ellipses: true, showSigma: true }); },
    },
    {
      title: 'Σ is the ellipse: eigenvectors and eigenvalues',
      description: 'The shape of those ellipses is exactly the eigen-structure of $\\Sigma$. The eigenvectors point along the principal axes; the eigenvalues are the variances along those axes, so each semi-axis has length proportional to $\\sqrt{\\lambda}$. Correlation is what rotates the axes away from the coordinate directions.',
      equation: '\\Sigma \\mathbf{v}_i = \\lambda_i \\mathbf{v}_i, \\qquad \\text{semi-axis}_i \\;\\propto\\; \\sqrt{\\lambda_i}',
      notes: 'This is a principal-axis / PCA view of the Gaussian: Σ tells you the natural coordinate frame of the cloud and how much it spreads in each. The teal arrows are the two eigenvectors, scaled by √λ.\n\nDrag ρ and the arrows swing round; set ρ = 0 with equal σ and both eigenvalues coincide — no preferred direction, so the ellipse becomes a circle.',
      setup(c2d, st) { clearControls(st); sxSlider(st); sySlider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { ellipses: true, axes: true, showEig: true }); },
    },
    {
      title: 'The Gaussian miracle: uncorrelated ⇒ independent',
      description: 'Set the correlation to zero. $\\Sigma$ turns diagonal, the ellipse straightens to axis-aligned, and the joint density factors cleanly into a bell in $x$ times a bell in $y$. A density that factors is the definition of independence. For the multivariate normal — and essentially only here — zero correlation genuinely means independent.',
      equation: '\\rho = 0 \\;\\Rightarrow\\; f(x, y) = f_{X_1}\\!(x)\\, f_{X_2}\\!(y) \\;\\Rightarrow\\; X_1 \\perp X_2',
      notes: 'This is the exception promised at the end of Covariance & Correlation. In general uncorrelated does NOT imply independent; in the Gaussian world the two coincide, because the density is built from ρ alone — kill it and nothing couples the coordinates.\n\nThe curves in the margins are the two factors $f_{X_1}$ and $f_{X_2}$. Slide ρ to 0 and the tilted cloud squares up to their product.',
      setup(c2d, st) { clearControls(st); rhoSlider(st); sxSlider(st); sySlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { ellipses: true, marginals: true, showCorr: true }); },
    },
    {
      title: 'Slice it and it is normal again',
      description: 'Fix one coordinate, $X_1 = x$, and ask about the other. The conditional distribution of $X_2$ is again normal, with a mean that moves linearly in $x$ — the population regression line — and a variance smaller than the marginal, shrunk by exactly the factor $1-\\rho^2$. Knowing $X_1$ pulls $X_2$ toward the line and sharpens it.',
      equation: 'X_2 \\mid X_1 = x \\;\\sim\\; \\mathcal{N}\\!\\Big(\\mu_2 + \\rho\\tfrac{\\sigma_2}{\\sigma_1}(x-\\mu_1),\\;\\; \\sigma_2^2(1-\\rho^2)\\Big)',
      notes: 'The green line is the regression line $\\mathbb{E}[X_2\\mid X_1=x]$; the orange bell is the conditional density on the slice, and its centre rides the line. This linear-conditional-mean, constant-conditional-variance structure is why the Gaussian underlies linear regression.\n\nDrag the slice across: the bell slides along the line without changing width. Turn ρ toward 0 and the line flattens and the conditional widens back to the full marginal; toward ±1 and it collapses onto the line.',
      setup(c2d, st) { clearControls(st); x0Slider(st); rhoSlider(st); },
      update(c2d, st) { c2d.clearPersistent(); draw(c2d, st, { conditional: true, showCond: true }); },
    },
  ],
};
